#!/usr/bin/env bash

LATEST_VERSION="mars"

if [ "$DOCKER_TAG" = "latest" ]; then
	ECLIPSE_VERSION=$LATEST_VERSION
else
	ECLIPSE_VERSION=$DOCKER_TAG
fi

if [ "$ECLIPSE_VERSION" = "oxygen" ]; then
	BASE_IMAGE=ubuntu:xenial
	ECLIPSE_TAR_URL=http://ftp.fau.de/eclipse/technology/epp/downloads/release/oxygen/2/eclipse-php-oxygen-2-linux-gtk-x86_64.tar.gz
elif [ "$ECLIPSE_VERSION" = "neon" ]; then
	BASE_IMAGE=ubuntu:xenial
	ECLIPSE_TAR_URL=http://ftp.fau.de/eclipse/technology/epp/downloads/release/neon/2/eclipse-php-neon-2-linux-gtk-x86_64.tar.gz
elif [ "$ECLIPSE_VERSION" = "mars" ]; then
	BASE_IMAGE=debian:jessie
        ECLIPSE_TAR_URL=http://ftp.fau.de/eclipse/technology/epp/downloads/release/mars/2/eclipse-php-mars-2-linux-gtk-x86_64.tar.gz
else
	echo "Need to specify base image"
	exit 1
fi

docker build -t ${IMAGE_NAME} \
	--build-arg=BASE_IMAGE=$BASE_IMAGE \
	--build-arg=ECLIPSE_VERSION=$ECLIPSE_VERSION \
	--build-arg=ECLIPSE_TAR_URL=$ECLIPSE_TAR_URL \
	.
